# Generated by Django 4.1.4 on 2023-01-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
