# Generated by Django 4.1.5 on 2023-01-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name', 'department']},
        ),
    ]
