# Generated by Django 4.1.5 on 2023-01-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_end_date_alter_employee_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='C:\\projects\\emp\\static'),
        ),
    ]
