# Generated by Django 4.1.4 on 2023-01-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('page_type', models.CharField(blank=True, default='C', max_length=1, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
