# Generated by Django 4.1.4 on 2023-01-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(blank=True, max_length=50, null=True)),
                ('setting_text', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ['setting_name'],
            },
        ),
    ]
