# Generated by Django 4.1.5 on 2023-01-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_systeminfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField(blank=True, default=0, null=True)),
                ('session_id', models.CharField(blank=True, max_length=50, null=True)),
                ('key_name', models.CharField(blank=True, max_length=50, null=True)),
                ('key_text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'ordering': ['session_id', 'key_name'],
            },
        ),
    ]
