# Generated by Django 4.1.5 on 2023-01-20 01:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sessioninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioninfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessioninfo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
