# Generated by Django 4.1.4 on 2023-01-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='filetype',
            field=models.CharField(choices=[('F', 'File'), ('U', 'URL')], default='L', max_length=1),
        ),
    ]
