# Generated by Django 4.1.4 on 2023-01-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_file_url_alter_file_file_alter_file_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Order',
            field=models.IntegerField(default=0),
        ),
    ]
