# Generated by Django 4.1.4 on 2023-01-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_file_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
