# Generated by Django 4.1.4 on 2023-01-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_file_order_alter_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/files/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
