# Generated by Django 4.1.4 on 2023-01-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_file_file_alter_file_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['name', 'page']},
        ),
        migrations.RenameField(
            model_name='file',
            old_name='group',
            new_name='page',
        ),
    ]
